application/models/Answer.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Answer extends ActiveRecord
{

    public static function tableName()
    {
        return 'answers';
    }

    public function attributeLabels()
    {
        return [
            'text' => 'Ваш ответ',
        ];
    }

    public function rules()
    {
        return [
            ['text', 'required'],
            ['text', 'trim'],
            ['text', 'string'],
            ['question_id', 'required'],
            ['question_id', 'integer'],
        ];
    }

    public function getAuthor()
    {
        return $this->hasOne(User::className(), ['id' => 'author_id']);
    }

    public function getQuestion()
    {
        return $this->hasOne(Question::className(), ['id' => 'question_id']);
    }

    public function beforeSave($insert)
    {
        $this->author_id = \Yii::$app->user->id;
        return true;
    }

}

application/models/Question.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Question extends ActiveRecord
{

    public static function tableName()
    {
        return 'questions';
    }

    public function attributeLabels()
    {
        return [
            'text' => 'Ваш вопрос',
        ];
    }

    public function rules()
    {
        return [
            ['text', 'required'],
            ['text', 'trim'],
            ['text', 'string', 'min' => 10],
        ];
    }

    public function getAuthor()
    {
        return $this->hasOne(User::className(), ['id' => 'author_id']);
    }

    public function getAnswers()
    {
        return $this->hasMany(Answer::className(), ['question_id' => 'id'])->orderBy('date DESC');

    }

    public function beforeSave($insert)
    {
        $this->author_id = \Yii::$app->user->id;
        return true;
    }

}

application/models/User.php
<?php

namespace app\models;

use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

class User extends ActiveRecord implements IdentityInterface
{

    public static function tableName()
    {
        return 'users';
    }

    public function attributeLabels()
    {
        return [
            'username' => 'Логин',
            'password' => 'Пароль',
            'name' => 'Имя',
        ];
    }

    public function rules()
    {
        return [
            [['username', 'password', 'name'], 'required', 'on' => 'register'],
            ['username', 'unique', 'on' => 'register'],

            ['username', 'required', 'on' => 'login', 'message' => 'Проверьте правильность логина'],
            ['password', 'required', 'on' => 'login', 'message' => 'Неверный пароль'],

            [['username', 'password', 'name'], 'trim'],
            [['username', 'password', 'name'], 'string'],
        ];
    }

    public function beforeSave($insert)
    {
        if (!isset($this->id)) {
            $this->password = \Yii::$app->security->generatePasswordHash($this->password);
        }

        return true;
    }

    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['access_token' => $token]);
    }

    public function getId()
    {
        return $this->id;
    }

    public function getAuthKey()
    {
        return $this->auth_key;
    }

    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }
}

application/controllers/ErrorController.php
<?php

namespace app\controllers;

use \yii\web\Controller;

class ErrorController extends Controller
{
    public function actionIndex()
    {

    }

    public function actionError()
    {
        $exception = \Yii::$app->errorHandler->exception;

        if ($exception !== null) {
            return $this->render('error', ['exception' => $exception, 'handler' => new \yii\web\ErrorHandler()]);
        }
    }
}

application/controllers/IndexController.php
<?php

namespace app\controllers;

use app\models\Answer;
use app\models\Question;
use \yii\web\Controller;
use \yii\data\ActiveDataProvider;

class IndexController extends Controller
{
    public function actionIndex()
    {
        $this->view->title = 'Сервис вопросов и ответов';

        $data = new ActiveDataProvider([
            'query' => Question::find()->with('answers', 'author')->orderBy('date DESC'),
            'pagination' => [
                'forcePageParam' => false,
                'pageSizeParam' => false,
                'pageSize' => 10,
            ],
        ]);
        $question = new Question();

        echo $this->render('index', [
            'data' => $data,
            'questionModel' => $question,
        ]);
    }

    public function actionQuestion()
    {
        if (\Yii::$app->request->isPost) {
            $model = new Question();
            $postData = \Yii::$app->request->post('Question');
            $model->setAttributes($postData);
            if ($model->save()) {
                \Yii::$app->session->setFlash('success', 'Ваш вопрос опубликован.');
            }
        }
        return $this->redirect('/');
    }

    public function actionAnswer()
    {
        if (\Yii::$app->request->isPost) {
            $model = new Answer();
            $postData = \Yii::$app->request->post('Answer');
            $model->setAttributes($postData);
            if ($model->save()) {
                \Yii::$app->session->setFlash('success', 'Ваш ответ на вопрос успешно добавлен.');
            }
        }
        return $this->redirect('/');
    }
}

application/controllers/UserController.php
<?php

namespace app\controllers;

use app\models\User;
use yii\bootstrap\ActiveForm;
use \yii\web\Controller;
use yii\web\Response;

class UserController extends Controller
{
    public function actionAuth()
    {
        $result = [];

        if (!\Yii::$app->user->isGuest) {
            return $this->redirect('/');
        }
        $model = new User();
        $model->setScenario('login');

        if (\Yii::$app->request->isPost) {

            $userData = \Yii::$app->request->post('User');
            $identity = User::findOne(['username' => $userData['username']]);

            if ($identity) {
                if (!empty($userData['password'])) {
                    if (\Yii::$app->security->validatePassword($userData['password'], $identity->password)) {
                        \Yii::$app->user->login($identity);
                        return $this->redirect('/');
                    } else {
                        $result['user-password'] = ['Неверный пароль'];
                    }
                } else {
                    $result['user-password'] = ['Неверный пароль'];
                }
            } else {
                $result['user-username'] = ['Проверьте правильность логина'];
            }

            if (\Yii::$app->request->isAjax) {
                \Yii::$app->response->format = Response::FORMAT_JSON;
                return $result;
            }
        }

        if (\Yii::$app->request->isAjax) {
            echo $this->renderAjax('auth', [
                'model' => $model
            ]);
        } else {
            echo $this->render('auth', [
                'model' => $model
            ]);
        }
    }

    public function actionRegister()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->redirect('/');
        }
        $model = new User();
        $model->setScenario('register');

        if (\Yii::$app->request->isPost) {

            $userData = \Yii::$app->request->post('User');
            $model->setAttributes($userData);

            if (\Yii::$app->request->post('reg', false)) {
                if ($model->save()) {
                    \Yii::$app->user->login($model);
                } else {
                    var_dump($model->getErrors());
                }
            }
        }
        return $this->redirect('/');
    }

    public function actionRegisterValidate()
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        if (\Yii::$app->request->isAjax) {

            if (\Yii::$app->user->isGuest) {
                $model = new User();
                $userData = \Yii::$app->request->post('User');
                $model->setAttributes($userData);

                return ActiveForm::validate($model);
            }
        }
        return [];
    }

    public function actionLogout()
    {
        if (!\Yii::$app->user->isGuest) {
            \Yii::$app->user->logout();
        }
        return $this->redirect('/');
    }
}

application/views/index/_answer.php
<div class="col-xl-10 col-lg-10 col-md-10 col-sm-10 pull-right">
    <p><strong><?=$model->author->name ?></strong>, <em><?=Yii::$app->formatter->asDatetime($model->date, 'php:d.m.Y H:i:s') ?></em></p>
    <blockquote>
        <?=$model->text ?>
    </blockquote>
</div>

application/views/index/_question.php
<?php

use \yii\helpers\Url;
use \yii\bootstrap\Html;
use \yii\bootstrap\ActiveForm;

$answerModel = new \app\models\Answer();

?>
<div class="row">
    <hr/>
    <p><strong><?=$model->author->name ?></strong>, <em><?=Yii::$app->formatter->asDatetime($model->date, 'php:d.m.Y H:i:s') ?></em></p>
    <blockquote>
        <?=$model->text ?>
    </blockquote>
    <p>
        <?=Html::a('Посмотреть ответы <span class="badge">'.count($model->answers).'</span> / Ответить', '#answers_' . $model->id, [
            'data-toggle' => 'collapse',
            'aria-expanded' => 'false',
            'aria-controls' => 'answers_' . $model->id,
        ]) ?>
    </p>
    <div class="collapse" id="answers_<?=$model->id ?>">

        <?php if (Yii::$app->user->isGuest) : ?>
            <div class="well text-center">
                <?=Html::a('Авторизируйтесь', Url::toRoute('user/auth'), [
                    'data-toggle' => 'modal',
                    'data-target' => '#modal'
                ])?>, чтоб иметь возможность задавать вопросы и оставлять ответы.
            </div>
        <?php else : ?>

            <?php $form = ActiveForm::begin([
                'id' => 'question-form',
                'layout' => 'horizontal',
                'action' => '/index/answer/',
                'enableAjaxValidation' => false,
            ]); ?>

            <?php echo $form->field($answerModel, 'text')->textarea(); ?>

            <div class="pull-right">
                <?=Html::activeHiddenInput($answerModel, 'question_id', ['value' => $model->id]) ?>
                <?=Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
            </div>
            <div class="clearfix"></div>

            <?php ActiveForm::end(); ?>

        <?php endif; ?>

        <?php foreach ($model->answers as $answer) {
            echo $this->render('_answer', ['model' => $answer]);
        } ?>
    </div>

</div>

application/views/index/index.php
<?php

use \yii\helpers\Url;
use \yii\bootstrap\Html;
use \yii\widgets\Pjax;
use \yii\widgets\ListView;
use \yii\bootstrap\ActiveForm;

?>
<div class="container">

    <?php

    $flashMessages = \Yii::$app->session->getAllFlashes();
    foreach ($flashMessages as $type => $message) {
        echo "<div class='alert alert-{$type}' role='alert'>{$message}</div>";
    }

    ?>

    <div class="jumbotron">
        <h2>Добро пожаловать на сайт вопросов и ответов</h2>
        <p>
            Здесь Вы найдете ответы на все интересующие Вас вопросы.<br/>
            А если вдруг не найдете, то можете задать вопрос, и знающие люди ответят Вам.
        </p>
    </div>

    <?php Pjax::begin(['id' => 'questionsList']) ?>
        <?php echo ListView::widget([
            'dataProvider' => $data,
            'itemView' => '_question',
            'summary' => 'Всего вопросов в нашей базе: {totalCount}',
            'layout' => "<h3>{summary}</h3><br>\n{items}\n<div class='text-center'>{pager}</div>"
        ]); ?>
    <?php Pjax::end() ?>

    <?php if (Yii::$app->user->isGuest) : ?>
        <div class="well text-center">
            <?=Html::a('Авторизируйтесь', Url::toRoute('user/auth'), [
                'data-toggle' => 'modal',
                'data-target' => '#modal'
            ])?>, чтоб иметь возможность задавать вопросы и оставлять ответы.
        </div>
    <?php else : ?>
        <div class="well text-center">
            <p>Задайте вопрос</p>
            <?php $form = ActiveForm::begin([
                'id' => 'question-form',
                'layout' => 'horizontal',
                'action' => '/index/question/',
                'enableAjaxValidation' => false,
            ]); ?>

            <?php echo $form->field($questionModel, 'text')->textarea(); ?>

            <hr/>
            <div class="pull-right">
                <?=Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
            </div>
            <div class="clearfix"></div>

            <?php ActiveForm::end(); ?>
        </div>
    <?php endif; ?>
</div>


<!-- Modal -->
<div class="modal fade" id="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>

application/views/layouts/main.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;

$this->beginPage();

?>
<!doctype html>
<html lang="ru">
    <head>
        <meta charset="<?= Yii::$app->charset; ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags(); ?>
        <title><?= Html::encode($this->title); ?></title>
        <?php $this->head(); ?>
    </head>
    <body>
        <?php $this->beginBody(); ?>
        <?php NavBar::begin([
            'brandLabel' => 'Questions & Answers'
        ]); ?>
            <?php if (!Yii::$app->user->isGuest) : ?>
                <p class="navbar-text pull-right">Вы вошли, как <?=Yii::$app->user->identity->name ?>. <?php echo Html::a('Выйти', '/user/logout/'); ?></p>
            <?php endif; ?>
            <?php echo Nav::widget([
                'id' => 'mainmenu',
                'options' => [
                    'class' => 'nav-pills pull-right'
                ],
                'items' => [
                    [
                        'label' => 'Войти',
                        'url' => ['user/auth'],
                        'visible' => Yii::$app->user->isGuest,
                        'linkOptions' => [
                            'data-toggle' => 'modal',
                            'data-target' => '#modal'
                        ],
                    ],
                ],
            ]);?>
        <?php NavBar::end();?>
        <?= $content; ?>
        <footer></footer>
        <?php $this->endBody(); ?>
    </body>
</html>
<?php $this->endPage(); ?>

application/views/user/auth.php
<?php

use \yii\helpers\Url;
use \yii\bootstrap\Html;
use \yii\bootstrap\ActiveForm;

?>


<div id="forms" class="carousel slide">
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Авторизация</h4>
            </div>
            <div class="modal-body">
                <?php

                $form = ActiveForm::begin([
                    'id' => 'auth-form',
                    'action' => 'user/auth/',
                    'layout' => 'horizontal',
                    'enableAjaxValidation' => true,
                    'validationUrl' => '/user/auth/',
                ]);

                echo $form->field($model, 'username');
                echo $form->field($model, 'password')->passwordInput();
                ?>

                <p class="text-center">Если у Вас нет аккаунта, Вы можете <?=Html::a('зарегистрироваться', '#', [
                        'data-target' => '#forms',
                        'data-slide-to' => "1",
                    ])?></p>

                <hr/>
                <div class="pull-right">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-primary">Войти</button>
                </div>
                <div class="clearfix"></div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
        <div class="item">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Регистрация</h4>
            </div>
            <div class="modal-body">
                <?php

                $form = ActiveForm::begin([
                    'id' => 'reg-form',
                    'action' => 'user/register/',
                    'layout' => 'horizontal',
                    'enableAjaxValidation' => true,
                    'validationUrl' => '/user/register-validate/',
                ]);

                echo $form->field($model, 'username');
                echo $form->field($model, 'password')->passwordInput();
                echo $form->field($model, 'name');
                ?>

                <p class="text-center">Если у Вас уже есть аккаунт, Вы можете <?=Html::a('авторизироваться', '#', [
                        'data-target' => '#forms',
                        'data-slide-to' => "0",
                    ])?></p>

                <hr/>
                <div class="pull-right">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-primary" name="reg" value="1">Зарегистрироваться</button>
                </div>
                <div class="clearfix"></div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>